name: ci

on:
  push:
    branches:
      - "environment"


jobs:
  build:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: $GITHUB_SHA
      BRANCH_REF: $GITHUB_REF
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v4
      - 
        name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - 
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - 
        name: Build and Push
        uses: docker/build-push-action@v6
        with:
          context: "{{defaultContext}}:environment"
          push: true
          tags: ${{ vars.DOCKERHUB_USERNAME }}/htb-2024-csc:${{ env.COMMIT_SHA }},${{ vars.DOCKERHUB_USERNAME }}/htb-2024-csc:${{ env.BRANCH_REF }},${{ vars.DOCKERHUB_USERNAME }}/htb-2024-csc:latest